"""Animasi Alpha Userbot"""
import asyncio
from collections import deque

from alpha import Message, alpha


@alpha.on_cmd("tiger$", about={"header": "Animasi Dikejar Harimau"})
async def alfareza_(message: Message):
    """Animasi Alpha Userbot Dikejar Harimau"""
    animation_interval = 0.0
    await message.edit("`HA HAAA.....`")
    await asyncio.sleep(1)
    await message.edit("`HARIIIMAAAUUUUU!!`")
    await asyncio.sleep(1)
    await message.edit("`🏃                        🐅`")
    await message.edit("`🏃                       🐅`")
    await message.edit("`🏃                      🐅`")
    await message.edit("`🏃                     🐅`")
    await message.edit("`🏃   `LARII`          🐅`")
    await message.edit("`🏃                   🐅`")
    await message.edit("`🏃                  🐅`")
    await message.edit("`🏃                 🐅`")
    await message.edit("`🏃                🐅`")
    await message.edit("`🏃               🐅`")
    await message.edit("`🏃              🐅`")
    await message.edit("`🏃             🐅`")
    await message.edit("`🏃            🐅`")
    await message.edit("`🏃           🐅`")
    await message.edit("`🏃WOARGH!   🐅`")
    await message.edit("`🏃           🐅`")
    await message.edit("`🏃            🐅`")
    await message.edit("`🏃             🐅`")
    await message.edit("`🏃              🐅`")
    await message.edit("`🏃               🐅`")
    await message.edit("`🏃                🐅`")
    await message.edit("`🏃                 🐅`")
    await message.edit("`🏃                  🐅`")
    await message.edit("`🏃                   🐅`")
    await message.edit("`🏃                    🐅`")
    await message.edit("`🏃                     🐅`")
    await message.edit("`🏃  Huh-Huh           🐅`")
    await message.edit("`🏃                   🐅`")
    await message.edit("`🏃                  🐅`")
    await message.edit("`🏃                 🐅`")
    await message.edit("`🏃                🐅`")
    await message.edit("`🏃               🐅`")
    await message.edit("`🏃              🐅`")
    await message.edit("`🏃             🐅`")
    await message.edit("`🏃            🐅`")
    await message.edit("`🏃           🐅`")
    await message.edit("`🏃          🐅`")
    await message.edit("`🏃         🐅`")
    await message.edit("`DIA SEMAKIN MENDEKAT!!!`")
    await asyncio.sleep(1)
    await message.edit("`🏃       🐅`")
    await message.edit("`🏃      🐅`")
    await message.edit("`🏃     🐅`")
    await message.edit("`🏃    🐅`")
    await message.edit("`Dahlah Pasrah Aja`")
    await asyncio.sleep(1)
    await message.edit("`🧎🐅`")
    await asyncio.sleep(2)
    await message.edit("`-TAMAT-`")
